name: tic_toc_toe
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dropdown_button2: ^1.9.1
  audioplayers: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: 'images/ic_launcher_background.png'
  adaptive_icon_foreground: 'images/ic_launcher_background.png'
  

flutter:


  uses-material-design: true

  assets:
    - images/
    - assets/
  

  fonts:
    - family: dana
      fonts:
        - asset: fonts\dm.ttf

